version: '3.8'
services:
  db:
    image: mariadb:10.5.13
    environment:
      MYSQL_DATABASE: 'vm'
      MYSQL_USER: 'vm'
      MYSQL_PASSWORD: 'vm'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - '3307:3306'
  vm:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db